### ISSUE TITLE
server never switches to websocket

### ISSUE THREAD

**Issue by vkurland** [codeminders/socket.io-server-java#6]
I am testing v1.0.3 with jetty 9.2.x (could not get jetty 9.4.x to work for me for unrelated reasons). Server-side socket-io servlet always uses long poll and never switches to websocket. I am attaching a screenshot of the Chrome developer tools panel that shows that the server always returns 200 and never 101 (protocol switch). I have seen the 101 response with socket-io library v1.0.2

Is there some special initialization I should do to enable websocket transport? I need the library to support both websocket and long poll.

![screenshot 2017-09-21 16 01 41](https://user-images.githubusercontent.com/3577460/30722626-24842554-9ee7-11e7-8d17-217b3a91322a.png)

**Comment by alexsaveliev** [comment]
@vkurland I'd like to see your code, if possible. It's hard to identify the reason of the problem now, sorry.

Some questions and ideas:
- how does your app looks? is it webapp (war) that runs by Jetty web server installed or it embeds Jetty web server?
- if your app embeds Jetty web server I'd suggest to check the following:
  - do you have runtime dependency on Jetty's websocket server implementation? Ensure that you do have `org.eclipse.jetty.websocket:javax-websocket-server-impl:${jetty.version}`
  - when you are configuring your embedded Jetty server, please add the following block:
```java
import org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer;
       .....
        ServletContextHandler context = ...
        .....
        WebSocketServerContainerInitializer.
                configureContext(context).
                addEndpoint(WebsocketTransportConnection.class);
```
This code is not required when your app runs as webapp from Jetty webserver, because at your app startup Jetty uses annotations to scan for available websocket `@ServerEndpoint`s

- there is a sample of embedded Jetty server +socket.io chat, see [ChatServer.java](https://github.com/codeminders/socket.io-server-java/blob/master/samples/jetty/src/main/java/com/codeminders/socketio/sample/jetty/ChatServer.java)

Catch me on Skype if you need further help

**Comment by vkurland** [comment]
thanks for getting back to me. I have opened access to my repo ( https://github.com/happygears/nw2 ), you should have the invite in your inbox. The most relevant stuff should be here :  https://github.com/happygears/nw2/tree/dev/backend/src/main/java/net/happygears/nw2/socket_io

and here

https://github.com/happygears/nw2/blob/dev/backend/src/main/java/net/happygears/nw2/WebServer.java

(method socketIOContext )

all of this is in the branch "dev"

I am going to try to implement your suggestion wth WebSocketServerContainerInitializer, I know I do not do this part right now. I'll post an update here once I have tried it

**Comment by vkurland** [comment]
I have added the call to WebSocketServerContainerInitializer...addEndpoint() as you suggested but this did not change anything. It did not break anything either so I have pushed the code to branch "dev".

To answer your questions:

 - this is embedded jetty. Currently I am using jetty 9.2.4. I could not get session management and authentication work with 9.4.x yet, they have changed this part very significantly.
 - I have added run time dependency on javax-websocket-server-impl. I had dependencies on websocket-api and websocket-servlet but I have cleaned this up and left only  javax-websocket-server-impl as you suggested.
 - I have added call to WebSocketServerContainerInitializer...addEndpoint()

**Comment by alexsaveliev** [comment]
The reason of the issue was custom configuration (custom context and path).

- added initialization examples in [com.codeminders.socketio.sample.jetty.ChatServer](https://github.com/codeminders/socket.io-server-java/blob/master/samples/jetty/src/main/java/com/codeminders/socketio/sample/jetty/ChatServer.java)
- documented websocket initialization options in README.md
